<a href="https://colab.research.google.com/github/CPukszta/gitbrachmerge/blob/main/homework/hw4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Set up Google Colab data path

In [1]:
# Colab setup ------------------
import os, sys, subprocess
if "google.colab" in sys.modules:
    cmd = "pip install --upgrade iqplot bebi103 watermark"
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = process.communicate()
    data_path = "https://s3.amazonaws.com/bebi103.caltech.edu/data/"
else:
    data_path = "../data/"
# ------------------------------

Import statements

In [68]:
import numpy as np
import pandas as pd
import random

import bokeh.io 
import bokeh.plotting
!pip install iqplot
import iqplot
!pip install bebi103
import bebi103

import scipy.stats

bokeh.io.output_notebook()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


/usr/local/lib/python3.7/dist-packages/bebi103/viz.py:40: UserWarning: DataShader import failed with error "No module named 'datashader'".
Features requiring DataShader will not work and you will get exceptions.
  Features requiring DataShader will not work and you will get exceptions."""


**Part A:** Set up the trivariate Normal Distribution using the parameters given in the homework

In [3]:
mu = np.array([10,15,25])
sigma = np.array([[6, -7, -5], [-7, 13, 11], [-5, 11, 10]])
num_samples = 2000

trivariate_samples = np.random.default_rng().multivariate_normal(mu, sigma, size=num_samples)
print("These are our 2000 samples of x = (x1, x2, x3) from the trivariate normal distribution")
print(trivariate_samples)

These are our 2000 samples of x = (x1, x2, x3) from the trivariate normal distribution
[[ 9.73470711 13.8410569  23.72109506]
 [ 9.38495383 12.60873502 22.07584485]
 [10.00019212 15.14139457 25.76559258]
 ...
 [13.20961966 13.27997391 24.95426067]
 [13.50013383 10.29113318 20.13198241]
 [ 9.14273256 16.30695328 25.25145339]]


Part B: Plot the samples of x1 as an ECDF. Overlap the CDF of the theoretical distribution for f(x1). Do they match?

> Indented block



We will start by finding our idealized $f(x1)$ computed by integrating the join pdf over x2 and x3. This gives us our $\mu$ and $\sigma$ for the distribution which we can then grab values from for plotting

In [25]:
# idealized f(x1)
mu_1 = mu[0] 
sigma_11 = sigma[0][0]
num_samples = 2000 
lin = np.linspace(0,20,100)

x1_norm = scipy.stats.norm.cdf(lin,loc=mu_1,scale = sigma_11)
x1_norm

array([0.04779035, 0.05123485, 0.05487403, 0.05871452, 0.06276288,
       0.06702552, 0.0715087 , 0.07621849, 0.08116073, 0.08634102,
       0.09176468, 0.09743671, 0.10336176, 0.10954411, 0.11598762,
       0.12269571, 0.12967134, 0.13691695, 0.14443448, 0.15222529,
       0.16029017, 0.1686293 , 0.17724224, 0.1861279 , 0.19528452,
       0.20470969, 0.21440029, 0.2243525 , 0.23456181, 0.24502299,
       0.25573012, 0.26667656, 0.27785498, 0.28925736, 0.30087502,
       0.31269861, 0.32471814, 0.33692303, 0.34930208, 0.36184356,
       0.37453521, 0.38736428, 0.40031755, 0.41338142, 0.42654189,
       0.43978468, 0.45309519, 0.46645861, 0.47985996, 0.49328412,
       0.50671588, 0.52014004, 0.53354139, 0.54690481, 0.56021532,
       0.57345811, 0.58661858, 0.59968245, 0.61263572, 0.62546479,
       0.63815644, 0.65069792, 0.66307697, 0.67528186, 0.68730139,
       0.69912498, 0.71074264, 0.72214502, 0.73332344, 0.74426988,
       0.75497701, 0.76543819, 0.7756475 , 0.78559971, 0.79529

Next, we will grab x1 from the trivariate distribution

In [23]:
x1_trivariate = trivariate_samples[:,0]


Plot the data!

In [28]:
p = iqplot.ecdf(data=x1_trivariate, legend_label = "X1 ECDF",width = 600, height =400)
p.line(lin,x1_norm,color="hotpink",legend_label = "X1 theoretical CDF")

bokeh.io.show(p)


**Part C)** Plot the samples of $x_1$ and $x_3$ together. Overlay a countour plot of the theoretical point pdf $f(x_1,x_3)$. Do these match up?

We already have the $x_1$ trivariate data and we will pull the $x_3$ triavariate data.

In [59]:
x3_trivariate = trivariate_samples[:,2]


35.352178075926986 15.051300913374687


Now we can go about computing the theoretical joint PDF $f(x_1,x_3)$. First we will section off the $\mu$ and $\sigma$ for the joint distribution. Then we establish a grid for our values which is determined by the min/max of our samples. Finally, we compute our mutivariate PDF.

In [65]:
mu_13 = [mu[0],mu[2]] 
sigma_x1x3 = [[sigma[0][0],sigma[0][2]],[sigma[2][0],sigma[2][2]]]

x1_min = x1_trivariate.min()
x1_max = x1_trivariate.max()
x3_min = x3_trivariate.min()
x3_max = x3_trivariate.max()

x1, x3 = np.mgrid[x1_min:x1_max:0.1,x3_min:x3_max:0.1]
pos =  np.dstack((x1, x3))

x1_x3_norm = scipy.stats.multivariate_normal.pdf(pos,
                                                 mean=mu_13,
                                                 cov=sigma_x1x3)
x1_x3_norm

array([[2.02770698e-16, 2.72916049e-16, 3.66697922e-16, ...,
        1.88911208e-05, 1.80150774e-05, 1.71502335e-05],
       [3.01136734e-16, 4.04731674e-16, 5.43032904e-16, ...,
        2.10528892e-05, 2.00479372e-05, 1.90582568e-05],
       [4.45945137e-16, 5.98500433e-16, 8.01868219e-16, ...,
        2.33950966e-05, 2.22465367e-05, 2.11181307e-05],
       ...,
       [1.52052867e-05, 1.58023744e-05, 1.63947794e-05, ...,
        3.79946174e-17, 2.79772059e-17, 2.05656338e-17],
       [1.34635895e-05, 1.39723088e-05, 1.44754137e-05, ...,
        2.52454878e-17, 1.85628908e-17, 1.36258294e-17],
       [1.18873834e-05, 1.23189350e-05, 1.27442872e-05, ...,
        1.67264823e-17, 1.22813480e-17, 9.00208182e-18]])

Now we can plot it all!

In [87]:
c = bokeh.plotting.figure(width = 500, height =300,
                          title = "Mulitvariate PDF",
                          x_axis_label ="X1 Distribution",y_axis_label ="X3 Distribution"    
)

bebi103.viz.contour(x1,x3,x1_x3_norm,p=c)
c.circle(x1_trivariate,x3_trivariate,legend_label="Trivariate Points")
bokeh.io.show(c)

The multivariate data points and the contour plot of the theoretical joint PDF line up quite well!

Attribution Statement: TODO

Watermark

In [8]:
%load_ext watermark
%watermark -v -p pandas,jupyterlab

Python implementation: CPython
Python version       : 3.7.15
IPython version      : 7.9.0

pandas    : 1.3.5
jupyterlab: not installed

